name: "Build Image"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["src/**"]

env:
  assembly-name: "template"
  tag: ghcr.io/${GITHUB_REPOSITORY,,}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Docker Image
        run: |
          docker build --tag ${{ env.tag }}:latest \
          --tag ${{ env.tag }}:$(echo $GITHUB_SHA | head -c7) \
          --build-arg assemby-name=${{ env.assembly-name }}
          -f Dockerfile.Image . 
          
      - name: Push Docker Image
        run: |
          docker push ${{ env.tag }}:latest
          docker push ${{ env.tag }}:$(echo $GITHUB_SHA | head -c7)
